# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-02 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prize', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='pic',
            field=models.ImageField(default='no-img.jpg', upload_to=''),
        ),
    ]
