"""
Django settings for auth project.

Generated by 'django-admin startproject' using Django 1.11.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ody(npyr2h5f+mwrw6y5&4n-58063(tlnr+5no%k2u&2#x-u_9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'authorization',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
]

ROOT_URLCONF = 'auth.urls'

TEMPLATES = [

]

WSGI_APPLICATION = 'auth.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

PRIVATE_KEY = """-----BEGIN RSA PRIVATE KEY-----
MIIBOwIBAAJBAJcbqAb6aNYQCFWagLngKAptIs2LfrCaZuFU4Qs9RiAvhvgRUBhi
alP9r3LiRfSVEULIQiiM61bcqMcQgclPBlkCAwEAAQJAbGixEeCRWhJCiHfCJpiE
4YYO0/xiNf1wFfU5R0D8kJWoAfH2of9YVSfP9C6wvcqr0nniJ1n6z9zGL97xeG2Z
AQIhAPKbNyeYXydlsbNX01bVz3l8uhVCVRWpUjavxEGGqJOJAiEAn3NI22+Gt5Ci
yhcq0+pt8iDG5oktjdzj71O3nRinmFECIE7cI16MigmtZcjtOHZWg91yrK4yZKPo
6R97nOjL08o5AiEAjXGe98l/H+dWAR98BnC3B0q8JlUZ6/Y+3FbPUrREN4ECIQCo
2c8Rnnt2+86YnZCqtS1KOfP70CQwOd/SQPhm1283sQ==
-----END RSA PRIVATE KEY-----"""